# Generated by Django 2.2.7 on 2019-11-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0002_delete_studentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemoryDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
            ],
        ),
    ]
