# Generated by Django 2.2.7 on 2019-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_usermemorydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemorydb',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
